### ISSUE TITLE
cannot find macro `llvm_asm` in this scope

### ISSUE THREAD

**Issue by zag2art** [avr-rust/blink#38]
hi, getting this during compiling
```
cargo build -Z build-std=core --target avr-atmega328p.json --release
...

   Compiling avr_delay v0.3.1
error: cannot find macro `llvm_asm` in this scope
  --> /Users/zag2art/.cargo/registry/src/github.com-1ecc6299db9ec823/avr_delay-0.3.1/src/lib.rs:34:17
   |
34 |         unsafe {llvm_asm!("1: sbiw $0,1
   |                 ^^^^^^^^

error: cannot find macro `llvm_asm` in this scope
  --> /Users/zag2art/.cargo/registry/src/github.com-1ecc6299db9ec823/avr_delay-0.3.1/src/lib.rs:41:13
   |
41 |     unsafe {llvm_asm!("1: sbiw $0,1
   |             ^^^^^^^^

```

is that an avr_delay issue or this blink project?

Note: compiling this on Mac folowing "The AVR-Rust Guidebook"

**Comment by stappersg** [comment]
> 
> Note: compiling this on Mac folowing "The AVR-Rust Guidebook"
> 

And what is the URL of "The AVR-Rust Guidebook"?

**Comment by zag2art** [comment]
https://book.avr-rust.com/003.3-example-building-blink.html

**Comment by stappersg** [comment]
It is https://github.com/avr-rust/delay/issues/10

**Comment by stappersg** [comment]
For what it is worth
```text
    ...
   Compiling avr-config v1.0.0
   Compiling avr-config v2.0.1
   Compiling avr-std-stub v1.0.2
   Compiling avr_delay v0.3.1
   Compiling blink v0.1.0 (/usr/src/rust/avr/blink)
    Finished release [optimized] target(s) in 33.68s
stappers@paddy:/usr/src/rust/avr/blink
$ cargo build -Z build-std=core --target avr-atmega328p.json --release
    Finished release [optimized] target(s) in 0.11s
stappers@paddy:/usr/src/rust/avr/blink
$ history | tail -n 6
 2070  rustup override set nightly-2021-01-07
 2071  cargo build -Z build-std=core --target avr-atmega328p.json --release
 2072  rustup component add rust-src
 2073  cargo build -Z build-std=core --target avr-atmega328p.json --release
 2074  cargo build -Z build-std=core --target avr-atmega328p.json --release
 2075  history | tail -n 6
stappers@paddy:/usr/src/rust/avr/blink
$ 
```

**Comment by zag2art** [comment]
Thanks
```
rustup override set nightly-2021-01-07
rustup component add rust-src
cargo build -Z build-std=core --target avr-atmega328p.json --release
```
Looks like it works only with nightly-2021-01-07 release.

**Comment by stappersg** [comment]
Re-opened.
To prevent new reports of it.

Those who are also bitten by this issue (can|should) put updates here.

**Comment by ShaneEverittM** [comment]
So currently the only solution is to use an old nightly compiler? Is the ultimate goal to change the implementation to not depend on `llvm_asm!`?

**Comment by stappersg** [comment]
The ultimate goal is a good live.


> So currently the only solution is to use an old nightly compiler? Is the ultimate goal to change the implementation to not depend on `llvm_asm!`?

Yes.  Indeed.

How long _currently_ will exist is unknown.  ( It is unknown to me how the _LLVM project_ moves forward )
Known there are _workaround projects_ such as https://www.reddit.com/r/rust/comments/tvtxpv/custom_rust_toolchain_for_avr/

**Comment by stappersg** [comment]
OKay, _LLVM project moved forward_, the [blocking bug is closed](https://github.com/rust-lang/compiler-builtins/issues/400#issuecomment-1122211690).

@mbuesch did [Fix build: Use the new rust asm! available in rustc 1.63.0-nightly](https://github.com/avr-rust/delay/pull/18) and [advised me](https://github.com/avr-rust/delay/issues/19#issuecomment-1133589844) on releasing `avr_delay` crate.

**Comment by stappersg** [comment]
Insteadof crates at https://crates.io are "crates" in git repositories used.

The error `cannot find macro llvm_asm in this scope` is solved.

**Comment by K4LCIFER** [comment]
Perhaps I'm missing something, but is  this issue not actually fixed yet? I cannot compile because it's looking for `llvm_asm`.

```
$ cargo build
info: syncing channel updates for 'nightly-x86_64-unknown-linux-gnu'
info: latest update on 2025-08-19, rust version 1.91.0-nightly (9eb4a2652 2025-08-18)
info: component 'rust-src' is up to date
warn: Force-skipping unavailable component 'rust-std-avr-unknown-gnu-atmega328'
   Compiling avr_delay v0.3.2
error: cannot find macro `llvm_asm` in this scope
  --> /home/<username>/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/avr_delay-0.3.2/src/lib.rs:34:17
   |
34 |         unsafe {llvm_asm!("1: sbiw $0,1
   |                 ^^^^^^^^

error: cannot find macro `llvm_asm` in this scope
  --> /home/<username>/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/avr_delay-0.3.2/src/lib.rs:41:13
   |
41 |     unsafe {llvm_asm!("1: sbiw $0,1
   |             ^^^^^^^^

error[E0635]: unknown feature `llvm_asm`
 --> /home/<username>/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/avr_delay-0.3.2/src/lib.rs:1:12
  |
1 | #![feature(llvm_asm)]
  |            ^^^^^^^^

For more information about this error, try `rustc --explain E0635`.
error: could not compile `avr_delay` (lib) due to 3 previous errors
```

**Comment by mbuesch** [comment]
You need to upgrade avr_delay to 0.4.2
